//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevitJames.AddinApplicationFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LevitJames.AddinApplicationFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string aafCloseSessionUserActionText {
            get {
                return ResourceManager.GetString("aafCloseSessionUserActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rtf]{0} has detected the Document you are working on is not editable.[cr2]The functionality of {0} will be limited until the document becomes editable. For more information please click on the following [link documents/noneditabledocuments.htm]link[-]..
        /// </summary>
        internal static string aafmsgDocumentNotEditable {
            get {
                return ResourceManager.GetString("aafmsgDocumentNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Not Editable.
        /// </summary>
        internal static string aafmsgDocumentNotEditableHeader {
            get {
                return ResourceManager.GetString("aafmsgDocumentNotEditableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running {0} version {1}.\n\nThis document contains {0} data from a newer Version, {2}.\nIf you continue, some data related to newer features may be lost.\nWould you like to continue?.
        /// </summary>
        internal static string aafmsgDowngradeDataWarning {
            get {
                return ResourceManager.GetString("aafmsgDowngradeDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The help page could not be found..
        /// </summary>
        internal static string aafmsgHelpUrlNotFound {
            get {
                return ResourceManager.GetString("aafmsgHelpUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username has not been set. Without setting
        ///your username, certain functions in Word will cease to properly function and {0} cannot run.
        ///
        ///Please enter your user name in the box below and click ok..
        /// </summary>
        internal static string aafmsgMissingUserName {
            get {
                return ResourceManager.GetString("aafmsgMissingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid master files folder: {0}.\n\nPlease contact your {1} administrator..
        /// </summary>
        internal static string aafmsgNetworkSyncInvalidMasterFilesFolderWarning {
            get {
                return ResourceManager.GetString("aafmsgNetworkSyncInvalidMasterFilesFolderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rtf]Your Master Files folder is improperly configured because it is set to the Shared sub folder. Set the Master Files folder one level higher.[cr2]Current Master Files location: {0}[cr]For more information please click [link Documents/step2establishthemas.htm]here[-]..
        /// </summary>
        internal static string aafmsgNetworkSyncMasterIsSharedWarning {
            get {
                return ResourceManager.GetString("aafmsgNetworkSyncMasterIsSharedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rtf]Your Master Files folder is improperly configured because it does not contain a Shared sub folder. Please verify that you have set the proper location in the Admin Settings.[cr2]Current Master Files location: {0}[cr]For more information please click [link Documents/step2establishthemas.htm]here[-]..
        /// </summary>
        internal static string aafmsgNetworkSyncMissingSharedFolderWarning {
            get {
                return ResourceManager.GetString("aafmsgNetworkSyncMissingSharedFolderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not registered correctly. Please re-register, or re-install the addin..
        /// </summary>
        internal static string aafmsgNotRegistered {
            get {
                return ResourceManager.GetString("aafmsgNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running {0} version {1}.\n\nThis document contains {0} data from a newer version, {2}.\nIf you continue, this data will be removed.\nWould you like to continue?.
        /// </summary>
        internal static string aafmsgRemoveFutureDataWarning {
            get {
                return ResourceManager.GetString("aafmsgRemoveFutureDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running {0} version {1}.\n\nThis document contains {0} data from a older version, {2}.\nIf you continue, this data will be removed.\nWould you like to continue?.
        /// </summary>
        internal static string aafmsgRemoveLegacyDataWarning {
            get {
                return ResourceManager.GetString("aafmsgRemoveLegacyDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata for {0} was successfully removed..
        /// </summary>
        internal static string aafmsgRemoveMetadataSucceeded {
            get {
                return ResourceManager.GetString("aafmsgRemoveMetadataSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove all {0} export data from the document.
        ///Are you sure?.
        /// </summary>
        internal static string aafmsgRemoveMetadataWarning {
            get {
                return ResourceManager.GetString("aafmsgRemoveMetadataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving application settings!.
        /// </summary>
        internal static string aafmsgSettingsErrorSavingWarning {
            get {
                return ResourceManager.GetString("aafmsgSettingsErrorSavingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inadequate privileges to change the application settings..
        /// </summary>
        internal static string aafmsgSettingsInadequatePrivilegesWarning {
            get {
                return ResourceManager.GetString("aafmsgSettingsInadequatePrivilegesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the application settings.
        /// </summary>
        internal static string aafmsgSettingsUnknownErrorWarning {
            get {
                return ResourceManager.GetString("aafmsgSettingsUnknownErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running {0} version {1}.\n\nThis document contains {0} data from a older Version, {2}.\nIf you continue, the data may not be readable on machines running older versions of {0}.\nWould you like to continue?.
        /// </summary>
        internal static string aafmsgUpgradeDataWarning {
            get {
                return ResourceManager.GetString("aafmsgUpgradeDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Word is incompatible..
        /// </summary>
        internal static string aafmsgWordVersionIncompatible {
            get {
                return ResourceManager.GetString("aafmsgWordVersionIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should be marked as dirty in the &apos;{1}&apos; transaction before calling the nested transaction &apos;{2}&apos;.
        /// </summary>
        internal static string aafVerifyDocStorage_BeginFailedForNestedTransaction {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_BeginFailedForNestedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something changed the state of {0} in the &apos;{1}&apos; transaction since the last transaction.
        /// </summary>
        internal static string aafVerifyDocStorage_BeginFailedForTransaction {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_BeginFailedForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Failed.
        /// </summary>
        internal static string aafVerifyDocStorage_CancelFailed {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_CancelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should be marked as dirty after completing nested transaction &apos;{1}&apos;.
        /// </summary>
        internal static string aafVerifyDocStorage_CommitFailedForNestedTransaction {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_CommitFailedForNestedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been modified after calling CompleteTransaction for transaction &apos;{1}&apos;.
        /// </summary>
        internal static string aafVerifyDocStorage_CommitFailedForTransaction {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_CommitFailedForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Failed.
        /// </summary>
        internal static string aafVerifyDocStorage_UndoFailed {
            get {
                return ResourceManager.GetString("aafVerifyDocStorage_UndoFailed", resourceCulture);
            }
        }
    }
}
